import type { PropertyWithRelations, SavedPet } from '@/types/database';

export const MOCK_SAVED_PETS: SavedPet[] = [
  {
    id: 'mock-saved-1',
    user_id: 'mock-user',
    client_name: 'Smith family',
    name: 'Buddy',
    species: 'dog',
    breed: 'Golden Retriever',
    age_category: 'senior',
    size_category: 'large',
    activity_level: 'low',
    indoor_outdoor: 'both',
    mobility_limitations: 'Hip dysplasia — minimize stairs',
    anxiety_sensitivity: 'moderate',
    escape_risk: 'low',
    special_notes: 'Loves sunbathing. Needs soft surfaces.',
    photo_url: null,
    last_used_at: '2026-05-10T12:00:00Z',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-05-10T12:00:00Z',
  },
  {
    id: 'mock-saved-2',
    user_id: 'mock-user',
    client_name: 'Smith family',
    name: 'Whiskers',
    species: 'cat',
    breed: 'Maine Coon',
    age_category: 'adult',
    size_category: 'large',
    activity_level: 'moderate',
    indoor_outdoor: 'indoor',
    mobility_limitations: null,
    anxiety_sensitivity: 'high',
    escape_risk: 'low',
    special_notes: 'Needs window perches and vertical space.',
    photo_url: null,
    last_used_at: '2026-05-10T12:00:00Z',
    created_at: '2026-03-01T10:00:00Z',
    updated_at: '2026-05-10T12:00:00Z',
  },
  {
    id: 'mock-saved-3',
    user_id: 'mock-user',
    client_name: 'Johnson family',
    name: 'Scout',
    species: 'dog',
    breed: 'Border Collie',
    age_category: 'young',
    size_category: 'medium',
    activity_level: 'very_high',
    indoor_outdoor: 'both',
    mobility_limitations: null,
    anxiety_sensitivity: 'low',
    escape_risk: 'high',
    special_notes: 'Known fence jumper. Needs daily intense exercise.',
    photo_url: null,
    last_used_at: '2026-04-28T09:00:00Z',
    created_at: '2026-02-15T10:00:00Z',
    updated_at: '2026-04-28T09:00:00Z',
  },
];

export const MOCK_PROPERTIES: PropertyWithRelations[] = [
  {
    id: 'mock-prop-1',
    user_id: 'mock-user',
    address: '742 Evergreen Terrace',
    city: 'Springfield',
    state: 'IL',
    postal_code: '62704',
    latitude: 39.7817,
    longitude: -89.6501,
    listing_description:
      'Charming 3-bedroom ranch on a quiet cul-de-sac. Spacious fenced backyard with mature shade trees. Single-story layout with hardwood floors throughout. Sunroom off the kitchen overlooks the garden. Mudroom entry from the garage with built-in storage. Walking distance to Centennial Park and local trails.',
    beds: 3,
    baths: 2,
    sqft: 1850,
    lot_size: '0.35 acres',
    property_type: 'single_family',
    stories: 1,
    flooring_type: 'hardwood',
    fencing_type: 'privacy',
    has_mudroom: true,
    has_pet_door: true,
    has_pet_wash_station: false,
    has_screened_porch: false,
    has_pool: false,
    has_built_in_pet_features: false,
    built_in_pet_features_desc: null,
    hoa_has_restrictions: false,
    hoa_pet_policy: null,
    hoa_breed_restrictions: null,
    hoa_pet_limit: null,
    notes: 'Great neighborhood. Seller has two dogs and says the yard is escape-proof. Privacy fence looks solid — 6ft cedar.',
    created_at: '2026-04-01T10:00:00Z',
    updated_at: '2026-04-01T10:00:00Z',
    pet_profiles: [
      {
        id: 'mock-pet-1',
        property_id: 'mock-prop-1',
        user_id: 'mock-user',
        name: 'Buddy',
        species: 'dog',
        breed: 'Golden Retriever',
        age_category: 'senior',
        size_category: 'large',
        activity_level: 'low',
        indoor_outdoor: 'both',
        mobility_limitations: 'Hip dysplasia',
        anxiety_sensitivity: 'moderate',
        escape_risk: 'low',
        special_notes: 'Loves sunbathing. Needs soft surfaces for resting.',
        photo_url: null,
        created_at: '2026-04-01T10:00:00Z',
        updated_at: '2026-04-01T10:00:00Z',
      },
      {
        id: 'mock-pet-2',
        property_id: 'mock-prop-1',
        user_id: 'mock-user',
        name: 'Whiskers',
        species: 'cat',
        breed: 'Maine Coon',
        age_category: 'adult',
        size_category: 'large',
        activity_level: 'moderate',
        indoor_outdoor: 'indoor',
        mobility_limitations: null,
        anxiety_sensitivity: 'high',
        escape_risk: 'low',
        special_notes: 'Needs window perches. Startles at loud noises.',
        photo_url: null,
        created_at: '2026-04-01T10:00:00Z',
        updated_at: '2026-04-01T10:00:00Z',
      },
    ],
    analyses: [
      {
        id: 'mock-analysis-1',
        property_id: 'mock-prop-1',
        user_id: 'mock-user',
        overall_score: 85,
        traffic_safety_score: 90,
        yard_score: 95,
        senior_comfort_score: 88,
        exercise_score: 72,
        indoor_comfort_score: 78,
        noise_stress_score: 82,
        red_flags_json: [
          'Hardwood floors may be slippery for senior dog with hip dysplasia — area rugs recommended',
          'No emergency vet within 5 miles',
        ],
        highlights_json: [
          'Securely fenced yard — the #1 feature pet-buying households want',
          'Single-story layout — ideal for senior dog with hip dysplasia',
          'Sunroom provides excellent window-watching for indoor cat',
          'Mudroom — practical entry point for pets and gear',
          'Pet door for independent outdoor access',
          'Quiet cul-de-sac — naturally quieter for noise-sensitive cat',
          '2 parks within walking distance',
          'No HOA pet restrictions',
        ],
        ai_summary:
          'This home is an excellent match for Buddy and Whiskers, scoring 85/100. The privacy-fenced backyard with mature shade trees is ideal for Buddy\'s gentle outdoor time, and the single-story ranch layout eliminates stair concerns for his hip dysplasia. Whiskers will love the sunroom — warm, light-filled, and perfect for a Maine Coon\'s sunbathing needs. The cul-de-sac location keeps noise low, which is crucial given Whiskers\' high anxiety sensitivity. The pet door gives Buddy independence, and the mudroom keeps post-walk mess contained.',
        agent_notes:
          'Lead with the sunroom and fenced yard during showing. The privacy fence is a huge selling point — mention the seller\'s confirmation that it\'s escape-proof. Position this as a "move-in ready pet home." Marketing angle: "Fully fenced backyard perfect for pets, single-story ranch ideal for families with senior dogs." Dog owners will love the mudroom + pet door combo.',
        scoring_details_json: {
          traffic_safety: { score: 90, reasoning: 'Cul-de-sac location significantly reduces traffic risk. Privacy fence adds safety buffer. No major roads nearby.' },
          yard: { score: 95, reasoning: 'Privacy-fenced 0.35-acre lot with mature shade trees — gold standard for dog owners. Seller confirms escape-proof. Excellent for both supervised and unsupervised outdoor time.' },
          senior_comfort: { score: 88, reasoning: 'Single-story eliminates all stair barriers. Pet door enables independent access. Sunroom provides warm resting spot. Hardwood is slightly slippery — area rugs recommended.' },
          exercise: { score: 72, reasoning: 'Centennial Park within walking distance. Yard adequate for gentle play. Limited trail access for more active needs.' },
          indoor_comfort: { score: 78, reasoning: 'Good natural light via sunroom. Mudroom for gear storage. Hardwood floors are attractive but vulnerable to scratches — consider scratch-resistant coating. Open layout good for pet navigation.' },
          noise_stress: { score: 82, reasoning: 'Quiet cul-de-sac. Detached home provides barking buffer. Some traffic noise from adjacent road. Good for noise-sensitive cat.' },
        },
        species_insights_json: {
          dog: {
            strengths: ['Privacy-fenced yard — #1 dog owner must-have', 'Mudroom for messy paws and gear storage', 'Pet door for independent outdoor access', 'Single-story — easy outdoor access for senior dog', 'Shaded outdoor area for resting'],
            concerns: ['Hardwood vulnerable to claw scratches over time', 'No pet wash station — consider adding one in mudroom'],
            must_haves_met: ['Securely fenced yard', 'Walkable neighborhood', 'Nearby parks (2)'],
            must_haves_missing: [],
            dealbreaker_risk: 'low',
          },
          cat: {
            strengths: ['Sunroom — cat paradise for sunbathing', 'Quiet cul-de-sac environment', 'Non-carpet flooring — easier litter and hairball cleanup'],
            concerns: ['No screened porch/catio for safe outdoor access', 'Could benefit from more vertical space'],
            must_haves_met: ['Good natural light and window access', 'Quiet environment'],
            must_haves_missing: [],
            dealbreaker_risk: 'low',
          },
        },
        marketing_tips_json: [
          'Lead with "fully fenced backyard perfect for pets" — the #1 conversion phrase for pet owners',
          'Highlight "no HOA pet restrictions" — builds trust fast',
          'Mention proximity to parks and trails — "dog-friendly neighborhood with nearby walking trails"',
          'Feature the sunroom as a pet-friendly highlight',
          'Show yard clearly in photos — wide angles with privacy fencing visible',
          'Stage the mudroom as a pet-friendly entry zone',
          'Use keywords "pet-friendly home" and "ideal for pet lovers" in listing',
        ],
        upgrade_suggestions_json: [
          { name: 'Add a pet washing station in mudroom', impact: 'medium' as const, description: 'The mudroom is already set up perfectly — adding a pet wash station would make this an emotional wow feature at showings.', estimated_cost: '$500–$1,500' },
          { name: 'Apply scratch-resistant floor coating', impact: 'low' as const, description: 'Polyurethane coating protects the hardwood from claw damage. Can market as "scratch-resistant hardwood" in listing.', estimated_cost: '$1–$3/sqft' },
          { name: 'Add screened porch or catio', impact: 'medium' as const, description: 'Would give the indoor cat safe outdoor experience — increasingly popular feature.', estimated_cost: '$1,000–$5,000' },
        ],
        map_context_json: null,
        created_at: '2026-04-01T10:05:00Z',
        updated_at: '2026-04-01T10:05:00Z',
      },
    ],
    analysis_photos: [],
  },
  {
    id: 'mock-prop-2',
    user_id: 'mock-user',
    address: '200 Lake Shore Drive, Unit 14C',
    city: 'Chicago',
    state: 'IL',
    postal_code: '60601',
    latitude: 41.8862,
    longitude: -87.6186,
    listing_description:
      'Modern 2-bed, 2-bath condo on the 14th floor with floor-to-ceiling windows and stunning lake views. Open concept living with quartz counters and stainless appliances. Building has rooftop dog run and is steps from Millennium Park. Heated garage parking included. LVP flooring throughout.',
    beds: 2,
    baths: 2,
    sqft: 1100,
    lot_size: 'N/A',
    property_type: 'condo',
    stories: 1,
    flooring_type: 'lvp',
    fencing_type: 'none',
    has_mudroom: false,
    has_pet_door: false,
    has_pet_wash_station: false,
    has_screened_porch: false,
    has_pool: false,
    has_built_in_pet_features: false,
    built_in_pet_features_desc: null,
    hoa_has_restrictions: true,
    hoa_pet_policy: 'Max 2 pets allowed. Monthly pet deposit $25. Pets must be leashed in common areas.',
    hoa_breed_restrictions: 'No aggressive breeds (pit bulls, rottweilers per building policy)',
    hoa_pet_limit: 2,
    notes: 'Building allows up to 2 pets. Monthly pet deposit required. Border collie should be fine breed-wise.',
    created_at: '2026-04-02T14:00:00Z',
    updated_at: '2026-04-02T14:00:00Z',
    pet_profiles: [
      {
        id: 'mock-pet-3',
        property_id: 'mock-prop-2',
        user_id: 'mock-user',
        name: 'Scout',
        species: 'dog',
        breed: 'Border Collie',
        age_category: 'young',
        size_category: 'medium',
        activity_level: 'very_high',
        indoor_outdoor: 'both',
        mobility_limitations: null,
        anxiety_sensitivity: 'low',
        escape_risk: 'high',
        special_notes: 'Extremely energetic. Known fence jumper. Needs daily runs and mental stimulation.',
        photo_url: null,
        created_at: '2026-04-02T14:00:00Z',
        updated_at: '2026-04-02T14:00:00Z',
      },
    ],
    analyses: [
      {
        id: 'mock-analysis-2',
        property_id: 'mock-prop-2',
        user_id: 'mock-user',
        overall_score: 45,
        traffic_safety_score: 55,
        yard_score: 18,
        senior_comfort_score: 75,
        exercise_score: 62,
        indoor_comfort_score: 72,
        noise_stress_score: 35,
        red_flags_json: [
          'No private yard — #1 dealbreaker for most dog owners (relies on building dog run only)',
          '14th floor with balcony + high-escape-risk dog = serious fall/safety concern',
          'Lake Shore Drive generates significant constant traffic noise',
          'Very high-energy Border Collie in 1100 sqft — likely behavioral issues without 2+ hours daily exercise',
          'HOA breed restrictions — verify Border Collie is approved (should be fine, but confirm)',
          'Shared walls — neighbors will hear barking, pet hears neighbors',
        ],
        highlights_json: [
          'Luxury vinyl plank flooring — durable, waterproof, pet-proof',
          'Millennium Park nearby for daily exercise',
          'Building has dedicated rooftop dog run',
          'Floor-to-ceiling windows provide excellent natural light',
          'Heated garage means no cold weather leash-up in winter',
        ],
        ai_summary:
          'This condo is a challenging match for Scout, scoring just 45/100. While the building offers pet-friendly amenities like a rooftop dog run and the LVP flooring is ideal, the fundamentals don\'t align with a very high-energy Border Collie. The 1100 sqft space with no private yard means Scout would need 2+ hours of daily park exercise — every single day — to stay healthy and avoid destructive behavior. The 14th-floor balcony is a genuine safety concern given Scout\'s escape history. Most dog owners would walk away from this one.',
        agent_notes:
          'Honest assessment: this is a tough match for this specific dog. If the buyer is committed to downtown living with Scout, emphasize Millennium Park access as a non-negotiable daily commitment (not optional). Ask building management about balcony enclosure options. Recommend they see ground-floor units instead — would score significantly higher. The LVP flooring is a genuine selling point worth highlighting. Disclose the HOA pet policy and breed restrictions upfront to build trust.',
        scoring_details_json: {
          traffic_safety: { score: 55, reasoning: 'Lake Shore Drive is a major arterial road. Building entrance requires crossing busy intersections. Indoor unit provides buffer, but daily walks expose the dog to traffic. Sidewalks are present.' },
          yard: { score: 18, reasoning: 'No private outdoor space — the single biggest negative. Rooftop dog run is shared, small, and doesn\'t substitute for a real yard. For a high-energy breed, this is fundamentally insufficient.' },
          senior_comfort: { score: 75, reasoning: 'N/A for this young dog. Elevator access, smooth LVP floors, single-level unit are all fine.' },
          exercise: { score: 62, reasoning: 'Millennium Park is excellent for runs and play — but requires leash walks on busy streets to reach it. No off-leash options confirmed nearby. Heated garage is a nice winter perk.' },
          indoor_comfort: { score: 72, reasoning: 'LVP flooring is the best-in-class pet flooring — waterproof, scratch-resistant. Great natural light from windows. But 1100 sqft is genuinely small for a Border Collie\'s energy level.' },
          noise_stress: { score: 35, reasoning: 'Lake Shore Drive traffic is constant and audible. Shared walls mean barking affects neighbors and vice versa. Wind noise on 14th floor.' },
        },
        species_insights_json: {
          dog: {
            strengths: ['LVP flooring — top-tier pet flooring', 'Heated garage for winter walks', 'Building dog run available', 'Elevator access — no stairs'],
            concerns: ['No private yard — #1 dealbreaker for dog owners', '1100 sqft very tight for high-energy medium dog', 'Balcony on 14th floor with escape-risk dog', 'Shared walls = barking concerns from neighbors', 'HOA requires pet deposit and leashing in common areas'],
            must_haves_met: ['Walkable neighborhood (with caveats — busy streets)'],
            must_haves_missing: ['No private fenced yard — often non-negotiable for dog owners', 'Insufficient space for very high-energy breed', 'No safe off-leash area on-site'],
            dealbreaker_risk: 'high',
          },
        },
        marketing_tips_json: [
          'This property is better suited for cat owners or small/low-energy dog owners',
          'If targeting pet owners: highlight the LVP flooring and rooftop dog run',
          'Lead with "pet-friendly building steps from Millennium Park"',
          'Disclose HOA pet policy upfront — transparency prevents late-stage deal collapse',
          'For a Border Collie owner specifically: recommend they look at ground-floor units with private patios',
        ],
        upgrade_suggestions_json: [
          { name: 'Install balcony safety enclosure', impact: 'high' as const, description: 'Critical safety upgrade for high-floor units with pets. Prevents escape/fall risk.', estimated_cost: '$500–$2,000' },
          { name: 'Add smart pet door to balcony (with enclosure)', impact: 'medium' as const, description: 'After securing the balcony, a smart pet door gives supervised outdoor access.', estimated_cost: '$200–$800' },
        ],
        map_context_json: null,
        created_at: '2026-04-02T14:05:00Z',
        updated_at: '2026-04-02T14:05:00Z',
      },
    ],
    analysis_photos: [],
  },
];
